import { NetworkNode, NetworkLink, TopologyData, NetworkFolder } from '../../../types/network';

export const INITIAL_FOLDERS: NetworkFolder[] = [];

export const INITIAL_TOPOLOGY: TopologyData = {
  id: 'topo-clean-v1',
  name: 'Topologia e Documentação de Rede',
  description: 'Infraestrutura de rede, POPs e rotas ópticas.',
  updatedAt: new Date().toISOString(),
  gridSnap: true,
  folders: [],
  nodes: [],
  links: [],
};

export const DEVICE_CATALOG: Array<{
  type: NetworkNode['type'];
  name: string;
  category: NetworkNode['category'];
  model: string;
  vendor: string;
  description: string;
  defaultPorts: NetworkNode['ports'];
  osType?: NetworkNode['osType'];
  defaultPowerDbm?: number;
  rackUnits?: number;
  powerSupply?: NetworkNode['powerSupply'];
}> = [
  // ISP Core & Roteamento
  {
    type: 'router_bgp',
    name: 'Roteador BGP Core 100G/10G',
    category: 'isp_core',
    model: 'CCR2116-12G-4S+',
    vendor: 'MikroTik',
    rackUnits: 1,
    powerSupply: 'Redundante AC/DC',
    description: 'Roteador BGP com 16 núcleos ARM 2GHz, 4 portas 10G SFP+ e 12 portas Gigabit RJ45.',
    osType: 'mikrotik_routeros',
    defaultPorts: [
      { id: 'p-sfp1', name: 'sfp-sfpplus1 (BGP Upstream)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-sfp2', name: 'sfp-sfpplus2 (BGP PTT/IX.br)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-sfp3', name: 'sfp-sfpplus3 (Downlink CGNAT)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-sfp4', name: 'sfp-sfpplus4 (Downlink Core)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-eth1', name: 'ether1 (Gerência)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-eth2', name: 'ether2 (Local/NOC)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
    ],
  },
  {
    type: 'router_cgnat',
    name: 'Concentrador PPPoE / CGNAT',
    category: 'isp_core',
    model: 'CCR2004-1G-12S+2XS',
    vendor: 'MikroTik',
    rackUnits: 1,
    powerSupply: 'Redundante AC/DC',
    description: 'Servidor BNG / PPPoE / CGNAT com 12 portas 10G SFP+ e 2 portas 25G SFP28.',
    osType: 'mikrotik_routeros',
    defaultPorts: [
      { id: 'p-sfp28-1', name: 'sfp28-1 (25G Uplink)', type: 'sfp_25g', mediaType: 'fiber', speedMode: '25G', status: 'up' },
      { id: 'p-sfp28-2', name: 'sfp28-2 (25G Uplink)', type: 'sfp_25g', mediaType: 'fiber', speedMode: '25G', status: 'up' },
      { id: 'p-sfp1', name: 'sfp-sfpplus1 (OLT Trunk 1)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-sfp2', name: 'sfp-sfpplus2 (OLT Trunk 2)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-sfp3', name: 'sfp-sfpplus3 (Switch Core)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-eth1', name: 'ether1 (OOB Mgmt)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
    ],
  },
  {
    type: 'router_bgp',
    name: 'Roteador Borda ISP Cisco ASR',
    category: 'isp_core',
    model: 'ASR 920-24SZ-M',
    vendor: 'Cisco',
    rackUnits: 1,
    powerSupply: 'DC -48V Telecom',
    description: 'Roteador de borda Carrier Ethernet com MPLS, BGP e 24 portas SFP/SFP+.',
    osType: 'cisco_ios',
    defaultPorts: [
      { id: 'p-te0', name: 'TenGigabitEthernet0/0/0', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-te1', name: 'TenGigabitEthernet0/0/1', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-ge0', name: 'GigabitEthernet0/0/2', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-mgmt', name: 'FastEthernet0 (Mgmt)', type: 'copper_100m', mediaType: 'ethernet', speedMode: '100M', status: 'up' },
    ],
  },

  // Switches Core / Distribuição / Acesso
  {
    type: 'switch_core',
    name: 'Switch Core L3 10G / 40G',
    category: 'isp_core',
    model: 'DM4370 24XG+2QG',
    vendor: 'Datacom',
    rackUnits: 1,
    powerSupply: 'Redundante AC/DC',
    description: 'Switch Layer 3 com 24 portas 10G SFP+ e 2 uplinks 40G QSFP+ para agregação NOC.',
    osType: 'generic',
    defaultPorts: [
      { id: 'p-q1', name: 'forty-gigabit-ethernet 1/1', type: 'sfp_40g', mediaType: 'fiber', speedMode: '40G', status: 'up' },
      { id: 'p-q2', name: 'forty-gigabit-ethernet 1/2', type: 'sfp_40g', mediaType: 'fiber', speedMode: '40G', status: 'up' },
      { id: 'p-x1', name: 'ten-gigabit-ethernet 1/1', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-x2', name: 'ten-gigabit-ethernet 1/2', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-x3', name: 'ten-gigabit-ethernet 1/3', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-x4', name: 'ten-gigabit-ethernet 1/4', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
    ],
  },
  {
    type: 'switch_access',
    name: 'Switch Acesso Gigabit 48P + 4x 10G PoE+',
    category: 'isp_core',
    model: 'CloudEngine S5735-L48P4X-A',
    vendor: 'Huawei',
    rackUnits: 1,
    powerSupply: 'AC 110/220V Bivolt',
    description: 'Switch de 48 portas 10/100/1000Base-T PoE+ e 4 portas 10GE SFP+ uplinks.',
    osType: 'huawei_vrp',
    defaultPorts: [
      { id: 'p-xge1', name: 'XGigabitEthernet0/0/1 (10G)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-xge2', name: 'XGigabitEthernet0/0/2 (10G)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-ge1', name: 'GigabitEthernet0/0/1 (PoE+)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', poe: 'poe_plus_at', status: 'up' },
      { id: 'p-ge2', name: 'GigabitEthernet0/0/2 (PoE+)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', poe: 'poe_plus_at', status: 'up' },
      { id: 'p-ge3', name: 'GigabitEthernet0/0/3 (PoE+)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', poe: 'poe_plus_at', status: 'up' },
      { id: 'p-ge4', name: 'GigabitEthernet0/0/4 (PoE+)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', poe: 'poe_plus_at', status: 'up' },
    ],
  },

  // OLTs GPON & Acesso FTTH
  {
    type: 'olt_gpon',
    name: 'OLT GPON Chassi Modular MA5800',
    category: 'access_ftth',
    model: 'SmartAX MA5800-X7',
    vendor: 'Huawei',
    rackUnits: 6,
    powerSupply: 'DC -48V Telecom',
    description: 'OLT modular Next-Gen com slots para até 112 portas GPON / XGS-PON e uplinks 100G/10G.',
    osType: 'huawei_vrp',
    defaultPowerDbm: 4.8,
    defaultPorts: [
      { id: 'p-up1', name: 'GE0/1 (Uplink 10G)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-up2', name: 'GE0/2 (Uplink 10G)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-pon1', name: 'GPON 0/1/0 (Slot 1)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.8, status: 'up' },
      { id: 'p-pon2', name: 'GPON 0/1/1 (Slot 1)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.8, status: 'up' },
      { id: 'p-pon3', name: 'GPON 0/1/2 (Slot 1)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.8, status: 'up' },
      { id: 'p-pon4', name: 'GPON 0/1/3 (Slot 1)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.8, status: 'up' },
    ],
  },
  {
    type: 'olt_gpon',
    name: 'OLT GPON Standalone 8/16 Portas',
    category: 'access_ftth',
    model: 'V1600G1-B 8-Port GPON',
    vendor: 'V-SOL / Fiberhome',
    rackUnits: 1,
    powerSupply: 'Redundante AC/DC',
    description: 'OLT 1U compacta com 8 portas GPON SC/UPC C+, 4 portas 10GE SFP+ e 8 portas GbE RJ45.',
    osType: 'generic',
    defaultPowerDbm: 4.5,
    defaultPorts: [
      { id: 'p-v-pon1', name: 'PON 1 (Class C+)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.5, status: 'up' },
      { id: 'p-v-pon2', name: 'PON 2 (Class C+)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.5, status: 'up' },
      { id: 'p-v-pon3', name: 'PON 3 (Class C+)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.5, status: 'up' },
      { id: 'p-v-pon4', name: 'PON 4 (Class C+)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: 4.5, status: 'up' },
      { id: 'p-v-sfp1', name: '10GE SFP+ Uplink 1', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-v-sfp2', name: '10GE SFP+ Uplink 2', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-v-eth1', name: 'GE Combo 1', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
    ],
  },

  // Centrais Telefônicas / PABX IP & Telefonia Telecom
  {
    type: 'telephony_pabx',
    name: 'Central Telefônica / PABX IP Híbrido',
    category: 'telephony_voip',
    model: 'CIP 800 / CIP 2000 IP PBX',
    vendor: 'Intelbras',
    rackUnits: 1,
    powerSupply: 'AC 110/220V Bivolt',
    description: 'Central PABX IP com suporte a Troncos SIP, portas FXS para ramais analógicos, portas FXO e E1.',
    osType: 'linux',
    defaultPorts: [
      { id: 'p-tel-eth1', name: 'LAN (SIP Trunk / Voip 1G)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-tel-eth2', name: 'WAN (Provedor SIP 1G)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-tel-e1', name: 'E1 Trunk (R2 / ISDN-PRI)', type: 'voice_e1', mediaType: 'voice', speedMode: 'auto', status: 'up' },
      { id: 'p-tel-fxo1', name: 'Linha FXO 1 (Analógica)', type: 'voice_fxo', mediaType: 'voice', speedMode: 'auto', status: 'up' },
      { id: 'p-tel-fxs1', name: 'Ramal FXS 1 (Diretoria)', type: 'voice_fxs', mediaType: 'voice', speedMode: 'auto', status: 'up' },
      { id: 'p-tel-fxs2', name: 'Ramal FXS 2 (NOC / Suporte)', type: 'voice_fxs', mediaType: 'voice', speedMode: 'auto', status: 'up' },
    ],
  },
  {
    type: 'telephony_pabx',
    name: 'Appliance PABX IP Grandstream UCM',
    category: 'telephony_voip',
    model: 'UCM6308 IP PBX 8 FXS / 8 FXO',
    vendor: 'Grandstream',
    rackUnits: 1,
    powerSupply: 'AC 110/220V Bivolt',
    description: 'Servidor PBX corporativo com 8 portas FXS, 8 portas FXO e 3 portas Gigabit com PoE.',
    osType: 'linux',
    defaultPorts: [
      { id: 'p-gs-lan', name: 'LAN 1 (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-gs-wan', name: 'WAN (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-gs-fxs1', name: 'Porta FXS 1', type: 'voice_fxs', mediaType: 'voice', speedMode: 'auto', status: 'up' },
      { id: 'p-gs-fxs2', name: 'Porta FXS 2', type: 'voice_fxs', mediaType: 'voice', speedMode: 'auto', status: 'up' },
      { id: 'p-gs-fxo1', name: 'Porta FXO 1', type: 'voice_fxo', mediaType: 'voice', speedMode: 'auto', status: 'up' },
    ],
  },

  // Servidores & Datacenter
  {
    type: 'server_datacenter',
    name: 'Servidor / Cache / DNS Recurso',
    category: 'isp_core',
    model: 'PowerEdge R650 1U',
    vendor: 'Dell',
    rackUnits: 1,
    powerSupply: 'Redundante AC/DC',
    description: 'Servidor de alta densidade para DNS Recurso / Unbound / Cache Netflix / BIND9.',
    osType: 'linux',
    defaultPorts: [
      { id: 'p-srv1', name: 'eth0 (10G SFP+ Data)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-srv2', name: 'eth1 (10G SFP+ Data)', type: 'sfp_10g', mediaType: 'fiber', speedMode: '10000M', status: 'up' },
      { id: 'p-srv3', name: 'idrac (Mgmt OOB 1G)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
    ],
  },

  // Energia, Nobreaks & PDUs de Rack
  {
    type: 'ups_nobreak',
    name: 'Nobreak Senoidal Online 3000VA (3kVA) 2U',
    category: 'rack_power',
    model: 'Smart-UPS RT 3000VA 2U Rack/Tower',
    vendor: 'APC by Schneider / NHS',
    rackUnits: 2,
    powerSupply: 'AC 110/220V Bivolt',
    capacityVa: 3000,
    totalOutlets: 8,
    batteryAutonomyMin: 45,
    description: 'Nobreak Senoidal de Dupla Conversão Online para alimentação ininterrupta de racks com 8 tomadas NBR 14136.',
    osType: 'generic',
    defaultPorts: [
      { id: 'p-ups-1', name: 'Tomada 01 (10A 220V)', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-ups-2', name: 'Tomada 02 (10A 220V)', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-ups-3', name: 'Tomada 03 (10A 220V)', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-ups-4', name: 'Tomada 04 (10A 220V)', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-ups-5', name: 'Tomada 05 (20A 220V)', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-ups-6', name: 'Tomada 06 (20A 220V)', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-ups-snmp', name: 'SNMP Card (Gerência 100M)', type: 'copper_100m', mediaType: 'ethernet', speedMode: '100M', status: 'up' },
    ],
  },
  {
    type: 'pdu_power_strip',
    name: 'Régua PDU 8 Tomadas 20A 1U Rack 19"',
    category: 'rack_power',
    model: 'PDU 8T 20A Voltímetro Digital',
    vendor: 'Max Eletron / Totem',
    rackUnits: 1,
    powerSupply: 'AC 110/220V Bivolt',
    totalOutlets: 8,
    description: 'Régua de distribuição de energia padrão 19" 1U com 8 tomadas NBR 14136 20A, cabo 2.5mm e voltímetro.',
    defaultPorts: [
      { id: 'p-pdu-1', name: 'Tomada PDU 1', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-2', name: 'Tomada PDU 2', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-3', name: 'Tomada PDU 3', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-4', name: 'Tomada PDU 4', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-5', name: 'Tomada PDU 5', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-6', name: 'Tomada PDU 6', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-7', name: 'Tomada PDU 7', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
      { id: 'p-pdu-8', name: 'Tomada PDU 8', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
    ],
  },
  {
    type: 'electrical_outlet',
    name: 'Tomada de Parede / Ponto Elétrico 20A',
    category: 'rack_power',
    model: 'Ponto Força 2P+T 20A 220V',
    vendor: 'Schneider / Pial',
    description: 'Ponto elétrico estabilizado derivado do QGBT com proteção de DPS Clamper e disjuntor.',
    defaultPorts: [
      { id: 'p-wall-out-1', name: 'Fase/Neutro/Terra 220V', type: 'power_outlet', mediaType: 'power_ac', status: 'up' },
    ],
  },
  {
    type: 'rectifier_power',
    name: 'Fonte Retificadora Telecom -48V DC',
    category: 'rack_power',
    model: 'DPR 2900B-48 Retificadora 1U',
    vendor: 'Delta / Emerson / Huawei',
    rackUnits: 1,
    powerSupply: 'DC -48V Telecom',
    description: 'Sistema de alimentação ininterrupta -48V DC com banco de baterias estacionárias e gerência SNMP.',
    osType: 'generic',
    defaultPorts: [
      { id: 'p-snmp', name: 'SNMP Ethernet (10/100M)', type: 'copper_100m', mediaType: 'ethernet', speedMode: '100M', status: 'up' },
      { id: 'p-dc1', name: 'Barramento DC 1 (-48V 50A)', type: 'console', mediaType: 'power_dc', speedMode: 'auto', status: 'up' },
      { id: 'p-dc2', name: 'Barramento DC 2 (-48V 50A)', type: 'console', mediaType: 'power_dc', speedMode: 'auto', status: 'up' },
    ],
  },

  // Racks & Gabinetes (Chão e Parede)
  {
    type: 'rack_floor',
    name: 'Rack 19" 44U de Chão Fechado',
    category: 'passive',
    model: 'Rack Servidor 44U 1000mm',
    vendor: 'Totem / Rittal',
    rackUnits: 44,
    totalRackCapacityU: 44,
    rackType: 'floor',
    description: 'Rack de chão padrão 19 polegadas 44U para abrigar ativos BGP, OLT, switches e servidores.',
    defaultPorts: [],
  },
  {
    type: 'rack_floor',
    name: 'Rack 19" 24U de Chão Datacenter',
    category: 'passive',
    model: 'Rack Telecom 24U 800mm',
    vendor: 'Totem / Max Eletron',
    rackUnits: 24,
    totalRackCapacityU: 24,
    rackType: 'floor',
    description: 'Rack de piso compacto 24U para POPs secundários e estações de distribuição.',
    defaultPorts: [],
  },
  {
    type: 'rack_wall',
    name: 'Rack de Parede 19" 9U 570mm',
    category: 'passive',
    model: 'Mini Rack Parede 9U',
    vendor: 'Intelbras / Max Eletron',
    rackUnits: 9,
    totalRackCapacityU: 9,
    rackType: 'wall',
    description: 'Rack de parede padrão 19" 9U para acomodar switch de acesso, PDU e patch panel.',
    defaultPorts: [],
  },
  {
    type: 'rack_wall',
    name: 'Rack de Parede 19" 12U 570mm',
    category: 'passive',
    model: 'Mini Rack Parede 12U',
    vendor: 'Max Eletron / Totem',
    rackUnits: 12,
    totalRackCapacityU: 12,
    rackType: 'wall',
    description: 'Rack de parede 12U com porta de vidro temperado e chaves para prédios e POPs.',
    defaultPorts: [],
  },

  // Cabeamento Estruturado, Patch Panels & DIOs
  {
    type: 'patch_panel_rj45',
    name: 'Patch Panel 24 Portas Cat6 1U',
    category: 'passive',
    model: 'Patch Panel Cat6 24P GigaLan',
    vendor: 'Furukawa / SohoPlus',
    rackUnits: 1,
    description: 'Painel de conexão RJ45 Cat6 1U para cabeamento estruturado e manobras de rede.',
    defaultPorts: [
      { id: 'p-pp-1', name: 'Porta 01', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-pp-2', name: 'Porta 02', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-pp-3', name: 'Porta 03', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-pp-4', name: 'Porta 04', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-pp-5', name: 'Porta 05', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-pp-6', name: 'Porta 06', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
    ],
  },
  {
    type: 'dio_fiber',
    name: 'DIO Óptico 24 FO 1U SC/APC',
    category: 'passive',
    model: 'DIO 1U 24 Fibras Rack 19"',
    vendor: 'Fibracem / Furukawa',
    rackUnits: 1,
    description: 'Distribuidor Interno Óptico padrão 19" com 24 acopladores SC/APC para terminação de cabos de fibra.',
    defaultPorts: [
      { id: 'p-dio-1', name: 'Fibra 01 (SC/APC)', type: 'pon_gpon', mediaType: 'fiber', status: 'up' },
      { id: 'p-dio-2', name: 'Fibra 02 (SC/APC)', type: 'pon_gpon', mediaType: 'fiber', status: 'up' },
      { id: 'p-dio-3', name: 'Fibra 03 (SC/APC)', type: 'pon_gpon', mediaType: 'fiber', status: 'up' },
      { id: 'p-dio-4', name: 'Fibra 04 (SC/APC)', type: 'pon_gpon', mediaType: 'fiber', status: 'up' },
    ],
  },
  {
    type: 'cable_organizer',
    name: 'Guia de Cabos Horizontal 1U',
    category: 'passive',
    model: 'Guia Cabos Fechado 1U 19"',
    vendor: 'Max Eletron / Totem',
    rackUnits: 1,
    description: 'Organizador frontal de cordões e patch cords para alinhamento e organização do rack.',
    defaultPorts: [],
  },
  {
    type: 'front_panel_blank',
    name: 'Frente Falsa 1U (Painel Cego)',
    category: 'passive',
    model: 'Painel Cego 1U 19" Aço',
    vendor: 'Totem / Max Eletron',
    rackUnits: 1,
    description: 'Painel cego para fechamento de espaços vazios no rack, otimizando fluxo de ar e estética.',
    defaultPorts: [],
  },
  {
    type: 'front_panel_blank',
    name: 'Frente Falsa 2U (Painel Cego)',
    category: 'passive',
    model: 'Painel Cego 2U 19" Aço',
    vendor: 'Totem / Rittal',
    rackUnits: 2,
    description: 'Painel cego 2U para fechamento de espaços maiores no rack.',
    defaultPorts: [],
  },
  {
    type: 'rack_tray',
    name: 'Bandeja Fixa para Rack 19" 1U',
    category: 'passive',
    model: 'Bandeja 1U 4 Pontos Fixação',
    vendor: 'Totem / Max Eletron',
    rackUnits: 1,
    description: 'Bandeja metálica perfurada para suporte de equipamentos não padrão rack 19" (modems, mini PCs, fontes).',
    defaultPorts: [],
  },

  // Acesso FTTH, Wireless & Clientes
  {
    type: 'onu_ont',
    name: 'ONU / ONT Wi-Fi 6 GPON',
    category: 'access_ftth',
    model: 'HG8145X6 Wi-Fi 6',
    vendor: 'Huawei',
    description: 'Terminal óptico residencial com Wi-Fi 6 Dual Band e 4 portas Gigabit RJ45.',
    defaultPowerDbm: -18.0,
    defaultPorts: [
      { id: 'p-onu-pon', name: 'Porta Óptica SC/APC (GPON)', type: 'pon_gpon', mediaType: 'pon', speedMode: '2.5G', opticalPowerDbm: -18.0, status: 'up' },
      { id: 'p-onu-lan1', name: 'LAN 1 (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-onu-lan2', name: 'LAN 2 (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-onu-pots', name: 'TEL 1 (POTS/FXS VoIP)', type: 'voice_fxs', mediaType: 'voice', speedMode: 'auto', status: 'up' },
      { id: 'p-onu-wifi', name: 'Wi-Fi 6 AX3000', type: 'wireless', mediaType: 'wireless', status: 'up' },
    ],
  },
  {
    type: 'wifi_router',
    name: 'Roteador Wi-Fi Mesh Gigabit',
    category: 'access_ftth',
    model: 'Twibi Force AX / Deco X20',
    vendor: 'Intelbras / TP-Link',
    description: 'Roteador sem fio Wi-Fi 6 com portas Gigabit Ethernet para residências e escritórios.',
    defaultPorts: [
      { id: 'p-wf-wan', name: 'WAN (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-wf-lan', name: 'LAN 1 (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
      { id: 'p-wf-air', name: 'Wi-Fi 5GHz / 2.4GHz', type: 'wireless', mediaType: 'wireless', status: 'up' },
    ],
  },
  {
    type: 'radio_ptp',
    name: 'Rádio PTP / Enlace Torre',
    category: 'wireless',
    model: 'AirFiber 5XHD / Mimosa B5c',
    vendor: 'Ubiquiti / Mimosa',
    description: 'Rádio Ponto a Ponto de alta capacidade (1 Gbps) para interligação de torres e POPs.',
    defaultPorts: [
      { id: 'p-rad-eth', name: 'Data / PoE In (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', poe: 'passive_48v', status: 'up' },
      { id: 'p-rad-rf', name: 'Enlace RF 5GHz MIMO', type: 'wireless', mediaType: 'wireless', status: 'up' },
    ],
  },
  {
    type: 'pc_workstation',
    name: 'PC / Estação de Trabalho',
    category: 'enterprise',
    model: 'OptiPlex 7000',
    vendor: 'Dell',
    description: 'Computador cliente para testes de conexão, ping, navegação e speedtest.',
    osType: 'generic',
    defaultPorts: [
      { id: 'p-pc-eth', name: 'Ethernet RJ45 (10/100/1000M)', type: 'copper_1g', mediaType: 'ethernet', speedMode: '1000M', status: 'up' },
    ],
  },
  {
    type: 'cto',
    name: 'CTO Atendimento (1x8 / 1x16)',
    category: 'passive',
    model: 'CTO 16 Portas IP65',
    vendor: 'Fibracem',
    description: 'Caixa de terminação óptica em poste para conexão de cabos drop aos clientes.',
    defaultPorts: [
      { id: 'p-cto-in', name: 'Entrada Fibra Tronco', type: 'pon_gpon', mediaType: 'pon', status: 'up' },
      { id: 'p-cto-p1', name: 'Porta Drop 01', type: 'pon_gpon', mediaType: 'pon', status: 'up' },
      { id: 'p-cto-p2', name: 'Porta Drop 02', type: 'pon_gpon', mediaType: 'pon', status: 'up' },
      { id: 'p-cto-p3', name: 'Porta Drop 03', type: 'pon_gpon', mediaType: 'pon', status: 'up' },
    ],
  },
  {
    type: 'ceo',
    name: 'Caixa de Emenda (CEO)',
    category: 'passive',
    model: 'CEO Domo 24 a 96 FO',
    vendor: 'Overtek',
    description: 'Caixa de emenda de fusão para sangrias e derivações de cabos tronco.',
    defaultPorts: [
      { id: 'p-ceo-in', name: 'Tronco In', type: 'pon_gpon', mediaType: 'pon', status: 'up' },
      { id: 'p-ceo-out', name: 'Derivação Out', type: 'pon_gpon', mediaType: 'pon', status: 'up' },
    ],
  },
  {
    type: 'internet_cloud',
    name: 'Nuvem / Trânsito / IX.br',
    category: 'cloud',
    model: 'Trânsito IP / PTT Metro',
    vendor: 'IX.br / Upstream',
    description: 'Conexão WAN com operadoras parceiras, trânsito global e pontos de troca.',
    defaultPorts: [
      { id: 'p-wan-1', name: 'Uplink 100G (QSFP28)', type: 'sfp_25g', mediaType: 'fiber', speedMode: '100G', status: 'up' },
    ],
  },
];
